FROM golang:1.22-alpine

RUN apk add --no-cache git ca-certificates wireguard-tools iptables
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod ./
RUN GOFLAGS=-mod=mod go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
